`define WR_VIDEO_WIDTH_24
`define DEF_WR_VIDEO_WIDTH 24
`define RD_VIDEO_WIDTH_24
`define DEF_RD_VIDEO_WIDTH 24
`define DEF_IMAGE_SIZE 21'h080000
`define WRITE_FIFO_DEPTH_2048
`define DEF_WRITE_FIFO_DEPTH 2048
`define READ_FIFO_DEPTH_2048
`define DEF_READ_FIFO_DEPTH 2048
`define READ_FIFO_BURST_MULT 4
`define DEF_ADDR_WIDTH 21
`define SRAM_DATA_WIDTH_64
`define DEF_SRAM_DATA_WIDTH 64
`define DEF_BURST_WRITE_LENGTH 128
`define DEF_BURST_READ_LENGTH 128
